name: fakesync

on:
  push:
    branches:
      - 'main'
    paths:
      - 'fakesync/**'
  workflow_dispatch:

jobs:

  rsyncd:
    name: Deploy fakesync Image
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: Publish fakesync Image
        uses: openzim/docker-publish-action@v10
        with:
          image-name: kiwix/fakesync
          on-master: latest
          restrict-to: kiwix/minibrain
          context: fakesync
          registries: ghcr.io
          credentials:
            GHCRIO_USERNAME=${{ secrets.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
